import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.css";
import { SearchProvider } from "../../utils/SearchContext";

const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Studio Ghibli Movies",
  description: "Generated by create next app",
  icons: {
    icon: "./favicon.co",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <head>
        <link rel="icon" href="./favicon.ico" sizes="any" />
      </head>
      <body className={jost.className}>
        <SearchProvider>{children}</SearchProvider>
      </body>
    </html>
  );
}
